version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nest_network

  nest_app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge